### ISSUE TITLE
python 3.12无法安装依赖Pillow~=10.1.0

### ISSUE THREAD

**Issue by LiebZhu** [HisAtri/LrcApi#103]
### 提交Issue之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。

### 问题描述

可以安装 Pillow更高版本无法兼容.

### 日志文件

python -m pip install Pillow~=10.1.0
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting Pillow~=10.1.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/80/d7/c4b258c9098b469c4a4e77b0a99b5f4fd21e359c2e486c977d231f52fc71/Pillow-10.1.0.tar.gz (50.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\vm01\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\vm01\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vm01\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\vm01\AppData\Local\Temp\pip-build-env-px8_8tcf\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vm01\AppData\Local\Temp\pip-build-env-px8_8tcf\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\vm01\AppData\Local\Temp\pip-build-env-px8_8tcf\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 30, in <module>
        File "<string>", line 27, in get_version
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### 系统信息

win10


### 补充信息

_No response_

**Comment by Nunan2589** [comment]
4281968384

**Comment by Nunan2589** [comment]
cd3cbd163c3ddba39e93cc995c922cf8effc5d84

**Comment by Nunan2589** [comment]
4281968384

**Comment by Nunan2589** [comment]
4281968384

**Comment by Nunan2589** [comment]
content/search-github/github-code-search/understanding-github-code-search-syntax.md

**Comment by Nunan2589** [comment]
4281968384
