### ISSUE TITLE
500错误

### ISSUE THREAD

**Issue by hiseab** [HisAtri/LrcApi#21]
### 提交Issue之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。

### 问题描述

2024-02-07 16:48:00,513 - ERROR - Exception on /jsonapi [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_caching/__init__.py", line 399, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask_caching/__init__.py", line 175, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 159, in lrc_json
    i = lrc.standard(i)
        ^^^^^^^^^^^^^^^
  File "/app/mod/lrc.py", line 9, in standard
    matches = pattern.findall(lrc_text)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

### 系统信息

docker

**Comment by HisAtri** [comment]
#23
