### ISSUE TITLE
500错误Internal Server Error

### ISSUE THREAD

**Issue by axdlee** [HisAtri/LrcApi#4]
docker部署后，访问 /lyrics?title=雨一直下
页面显示：Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

日志错误记录：
`2023-11-15 09:53:50,438 - ERROR - Exception on /lyrics [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_caching/__init__.py", line 404, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_caching/__init__.py", line 180, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
  File "/app/app.py", line 84, in lyrics
    path = unquote_plus(request.args.get('path'))
  File "/usr/local/lib/python3.9/urllib/parse.py", line 799, in unquote_plus
    string = string.replace('+', ' ')
AttributeError: 'NoneType' object has no attribute 'replace'`

**Comment by HisAtri** [comment]
错误出在URI参数里没有path这个key；URI参数需要带上path=，可以留空。

例如：`http://api.host/lyrics?title=雨一直下&artist=&album=&path=`
