### ISSUE TITLE
使用音流客户端时，保存歌词时弹出"歌词确认异常"

### ISSUE THREAD

**Issue by jesongit** [HisAtri/LrcApi#59]
### 提交Issue之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。

### 问题描述

如标题所示

### 日志文件

并未发现相关关键词日志，这个报错好像跟问题没什么关系
```
2024-06-21 10:55:35,375 - ERROR - Exception on /cover [HEAD]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask_caching/__init__.py", line 399, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask_caching/__init__.py", line 175, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/cover.py", line 37, in cover_api
    title = unquote_plus(request.args.get('title'))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 810, in unquote_plus
    string = string.replace('+', ' ')
             ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
2024-06-21 10:55:35,551 - ERROR - Exception on /cover [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask_caching/__init__.py", line 399, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask_caching/__init__.py", line 175, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/cover.py", line 37, in cover_api
    title = unquote_plus(request.args.get('title'))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/parse.py", line 810, in unquote_plus
    string = string.replace('+', ' ')
             ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
2024-06-21 11:50:29,565 - INFO - 正在启动服务器
2024-06-21 11:50:29,565 - INFO - 正在检查更新，当前版本
2024-06-21 11:50:29,579 - INFO - Serving on http://0.0.0.0:28883
2024-06-21 11:50:29,982 - INFO - 当前已是最新版本
2024-06-21 12:02:06,696 - INFO - Error: 
```

### 系统信息

环境使用docker搭建 + nginx proxy manager 反代 + 音流安卓客户端（ver: 1.29)
```yaml
# docker-compose.yaml
version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    environment:
      #程序默认语言
      - ND_DEFAULTLANGUAGE=zh-Hans
      #启用GRAVATAR头像
      - ND_ENABLEGRAVATAR=true
      #关闭转码，如需要转码请设置为true
      - ND_ENABLETRANSCODINGCONFIG=true
    volumes:
      - "/share/Container/navidrome:/data"
      - "/share/Video/Link/Music/Completed:/music:ro"
    restart: always
  lrcapi:
    image: hisatri/lrcapi:latest
    container_name: lrcapi
    ports:
      - 28883:28883
    volumes:
      - /share/Video/Link/Music/Completed:/music:ro
    restart: always
```

### 补充信息

请求歌词有最近一次请求得内容显示，但是确认接口没地方查看日志，docker并未发现与之相关的报错
是否可以加上类似日志得功能，以方便定位相关问题

**Comment by jesongit** [comment]
另外可以看看docker这个封面接口报错是什么问题

**Comment by TooAndy** [comment]
我最近在使用这个项目, 也发现了这个问题, 现在正在写 confirm 接口, 可以推 MR 给作者.

**Comment by HisAtri** [comment]
736bd0948d1cecba7bbf1abe9e44397624050706 现在给确认接口新增了一些日志输出，可能可以帮助定位错误原因

**Comment by HisAtri** [comment]
此问题已关闭，以更详细的Issue(#92)为准。更多内容请参阅该Issue。
