### ISSUE TITLE
歌手头像依然无法获取，

### ISSUE THREAD

**Issue by qingkeee** [HisAtri/LrcApi#73]
### 提交Issue之前，你应当知道：

- [X] Issue是用于快速定位和解决问题的，而不是这个项目的评论区。
- [X] 一个简明扼要的标题可以快速定位关键信息，标题不需要长篇大论，也不应过于宽泛。

### 问题描述

还有个问题，更新很多次之后，还是提示1.5.4，发现新版本1.5.5。
![PixPin_2024-09-27_22-58-45](https://github.com/user-attachments/assets/2128d4ca-faa4-44c9-9227-0f57a5be6176)

### 日志文件

2024-09-27T14:47:32.251200028Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:47:32.251206926Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 883, in full_dispatch_request
2024-09-27T14:47:32.251213746Z     return self.finalize_request(rv)
2024-09-27T14:47:32.251220321Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:47:32.251226833Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in finalize_request
2024-09-27T14:47:32.251233685Z     response = self.make_response(rv)
2024-09-27T14:47:32.251239993Z                ^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:47:32.251246402Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1174, in make_response
2024-09-27T14:47:32.251253050Z     raise TypeError(
2024-09-27T14:47:32.251259816Z TypeError: The view function for 'inner' did not return a valid response. The function either returned None or ended without a return statement.
2024-09-27T14:47:33.417482505Z Error: 'NoneType' object has no attribute 'replace'
2024-09-27T14:47:33.419587352Z 2024-09-27 14:47:33,418 - ERROR - Exception on /cover [HEAD]
2024-09-27T14:47:33.419643110Z Traceback (most recent call last):
2024-09-27T14:47:33.419657654Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
2024-09-27T14:47:33.419668354Z     response = self.full_dispatch_request()
2024-09-27T14:47:33.419676840Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:47:33.419686362Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 883, in full_dispatch_request
2024-09-27T14:47:33.419695635Z     return self.finalize_request(rv)
2024-09-27T14:47:33.419704167Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:47:33.419713102Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in finalize_request
2024-09-27T14:47:33.419721896Z     response = self.make_response(rv)
2024-09-27T14:47:33.419730457Z                ^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:47:33.419738827Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1174, in make_response
2024-09-27T14:47:33.419747597Z     raise TypeError(
2024-09-27T14:47:33.419756026Z TypeError: The view function for 'inner' did not return a valid response. The function either returned None or ended without a return statement.
2024-09-27T14:47:33.494319694Z Error: 'NoneType' object has no attribute 'replace'
2024-09-27T14:47:33.495961517Z 2024-09-27 14:47:33,494 - ERROR - Exception on /cover [GET]
2024-09-27T14:47:33.496002423Z Traceback (most recent call last):
2024-09-27T14:47:33.496013527Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
2024-09-27T14:47:33.496022328Z     response = self.full_dispatch_request()
2024-09-27T14:47:33.496029488Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:47:33.496036497Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 883, in full_dispatch_request
2024-09-27T14:47:33.496049176Z     return self.finalize_request(rv)
2024-09-27T14:47:33.496057268Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:47:33.496064159Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in finalize_request
2024-09-27T14:47:33.496071363Z     response = self.make_response(rv)
2024-09-27T14:47:33.496077930Z                ^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:47:33.496084816Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1174, in make_response
2024-09-27T14:47:33.496091964Z     raise TypeError(
2024-09-27T14:47:33.496098977Z TypeError: The view function for 'inner' did not return a valid response. The function either returned None or ended without a return statement.
2024-09-27T14:48:02.309801727Z Error: 'NoneType' object has no attribute 'replace'
2024-09-27T14:48:02.312039635Z 2024-09-27 14:48:02,311 - ERROR - Exception on /cover [HEAD]
2024-09-27T14:48:02.312078730Z Traceback (most recent call last):
2024-09-27T14:48:02.312091066Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
2024-09-27T14:48:02.312099390Z     response = self.full_dispatch_request()
2024-09-27T14:48:02.312106973Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:48:02.312113790Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 883, in full_dispatch_request
2024-09-27T14:48:02.312121530Z     return self.finalize_request(rv)
2024-09-27T14:48:02.312128266Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:48:02.312134851Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in finalize_request
2024-09-27T14:48:02.312141658Z     response = self.make_response(rv)
2024-09-27T14:48:02.312148234Z                ^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:48:02.312154693Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1174, in make_response
2024-09-27T14:48:02.312161703Z     raise TypeError(
2024-09-27T14:48:02.312168205Z TypeError: The view function for 'inner' did not return a valid response. The function either returned None or ended without a return statement.
2024-09-27T14:48:02.349684773Z Error: 'NoneType' object has no attribute 'replace'
2024-09-27T14:48:02.351357766Z 2024-09-27 14:48:02,350 - ERROR - Exception on /cover [GET]
2024-09-27T14:48:02.351443168Z Traceback (most recent call last):
2024-09-27T14:48:02.351461420Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
2024-09-27T14:48:02.351470804Z     response = self.full_dispatch_request()
2024-09-27T14:48:02.351478493Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:48:02.351486130Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 883, in full_dispatch_request
2024-09-27T14:48:02.351494272Z     return self.finalize_request(rv)
2024-09-27T14:48:02.351501857Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:48:02.351509245Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in finalize_request
2024-09-27T14:48:02.351516384Z     response = self.make_response(rv)
2024-09-27T14:48:02.351523382Z                ^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:48:02.351529989Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1174, in make_response
2024-09-27T14:48:02.351537213Z     raise TypeError(
2024-09-27T14:48:02.351544672Z TypeError: The view function for 'inner' did not return a valid response. The function either returned None or ended without a return statement.
2024-09-27T14:48:15.158263551Z Error: 'NoneType' object has no attribute 'replace'
2024-09-27T14:48:15.159325497Z 2024-09-27 14:48:15,158 - ERROR - Exception on /cover [HEAD]
2024-09-27T14:48:15.159354876Z Traceback (most recent call last):
2024-09-27T14:48:15.159361593Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
2024-09-27T14:48:15.159366143Z     response = self.full_dispatch_request()
2024-09-27T14:48:15.159370567Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:48:15.159374105Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 883, in full_dispatch_request
2024-09-27T14:48:15.159377552Z     return self.finalize_request(rv)
2024-09-27T14:48:15.159380876Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:48:15.159384123Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in finalize_request
2024-09-27T14:48:15.159387549Z     response = self.make_response(rv)
2024-09-27T14:48:15.159390771Z                ^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:48:15.159393972Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1174, in make_response
2024-09-27T14:48:15.159397662Z     raise TypeError(
2024-09-27T14:48:15.159400988Z TypeError: The view function for 'inner' did not return a valid response. The function either returned None or ended without a return statement.
2024-09-27T14:48:16.385802986Z Error: 'NoneType' object has no attribute 'replace'
2024-09-27T14:48:16.387282199Z 2024-09-27 14:48:16,386 - ERROR - Exception on /cover [GET]
2024-09-27T14:48:16.387322248Z Traceback (most recent call last):
2024-09-27T14:48:16.387365485Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
2024-09-27T14:48:16.387376984Z     response = self.full_dispatch_request()
2024-09-27T14:48:16.387384199Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:48:16.387391045Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 883, in full_dispatch_request
2024-09-27T14:48:16.387398059Z     return self.finalize_request(rv)
2024-09-27T14:48:16.387404232Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:48:16.387410529Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in finalize_request
2024-09-27T14:48:16.387417308Z     response = self.make_response(rv)
2024-09-27T14:48:16.387423837Z                ^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T14:48:16.387430468Z   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1174, in make_response
2024-09-27T14:48:16.387442337Z     raise TypeError(
2024-09-27T14:48:16.387449244Z TypeError: The view function for 'inner' did not return a valid response. The function either returned None or ended without a return statement.

### 系统信息

极空间

**Comment by qingkeee** [comment]
![Uploading PixPin_2024-09-27_23-03-11.png…]()

**Comment by qingkeee** [comment]
![Uploading PixPin_2024-09-27_23-03-11.png…]()

**Comment by EternalSunLhx** [comment]
same problem~

**Comment by HisAtri** [comment]
与 <https://github.com/HisAtri/LrcApi/issues/52#issuecomment-2254606857> 重复，已在 #78 中解决
